version: "3.2"
services:
  crm-service:
    container_name: crm-service
    build:
      context: .
      dockerfile: Dockerfile
    image: crm-service
    ports:
      - "3201:3201"
    env_file:
      - .env
